Towards pydantic dataclass
wtsi-npg/npg_langqc pull request #210
Opened 2024-03-05 12:32 UTC by mgcam

2024-03-05 16:33 UTC, nerdstrike approved these changes
I see nothing bad here. I think you've found the best way yet.

2024-03-07 14:09 UTC, nerdstrike requested changes
One minor doc error to correct.

I like the approach. We could at some point extend pydantic.base_model to include the `get_field_names` method so it is usable everywhere. `pre_root` is almost general, but still knows about the sqlalchemy table it maps to. Do you think we can meaningfully have a table-mapping `pre_root` that can do the job for any sqlalchemy-single-table -> class transformation?

2024-03-07 14:09 UTC, nerdstrike commented on lang_qc/models/pacbio/well.py
> +    giving it the an ORM object representing a database row with information
Minor grammar confusion.

2024-03-07 14:31 UTC, mgcam commented
> Do you think we can meaningfully have a table-mapping `pre_root` that can do the job for any sqlalchemy-single-table -> class transformation?

Yes, to some degree. I expect we will factor out some functionality into stand-alone functions as we convert more classes ot this type of model.

2024-03-07 16:32 UTC, nerdstrike approved these changes

2024-03-07 16:32 UTC, merged