Refactored assignment of QC states
wtsi-npg/npg_langqc pull request #74
Opened 2022-11-04 11:58 UTC by mgcam

2022-11-10 14:41 UTC, nerdstrike requested changes
Big improvement, but I have concerns about code readability.

2022-11-11 17:30 UTC, mgcam commented on lang_qc/db/helper/well.py
> +class WellMetrics(BaseModel):
The fact that it is single use allows for caching of results of computation in cached properties

2022-11-11 17:38 UTC, mgcam commented on lang_qc/db/helper/well.py
> +                select(QcStateDict).where(QcStateDict.state == qc_state)
Good point

2022-11-11 17:40 UTC, mgcam commented on lang_qc/endpoints/pacbio_well.py
> +    is flagged as preliminary. Not every authenticated user is allowed to perform QC.
Yes it is. The user should be listed in the `user` table.

2022-11-11 17:42 UTC, mgcam commented on lang_qc/models/qc_state.py
> +        # TODO: dates should be converted to local time, including DST
Agree

2022-11-14 14:41 UTC, nerdstrike commented
Naïvely the full stack seems to work with this set of changes.

2022-11-14 16:53 UTC, nerdstrike requested changes
A few more docstring troubles.

2022-11-14 16:53 UTC, nerdstrike commented on lang_qc/db/helper/well.py
> +        If the corresponding database record exists, this object corresponds
This is not an object, it's a property. Therefore more simply "Returns a pre-existing SeqProduct, or creates a new one."?

2022-11-15 11:38 UTC, nerdstrike approved these changes

2022-11-15 11:39 UTC, merged