Refactor non-inbox queries (spped up and correct sort)
wtsi-npg/npg_langqc pull request #91
Opened 2022-12-22 19:16 UTC by mgcam

Built on the top of https://github.com/wtsi-npg/npg_langqc/pull/89

2023-01-05 15:48 UTC, nerdstrike requested changes
All good, a couple of typos and quibbles.

2023-01-06 14:14 UTC, mgcam commented on lang_qc/db/helper/wells.py
> +            db_well = (
I think brackets are added bt `black`. I'll see whether this interference can be stopped.

2023-01-06 14:42 UTC, mgcam commented on lang_qc/db/helper/wells.py
> +            db_well = (
No, cannot do anything.

2023-01-06 14:49 UTC, nerdstrike commented on lang_qc/db/helper/wells.py
> +            db_well = (
Not to worry then...

2023-01-09 17:06 UTC, merged